<?php
/**
 * @file
 * Information about the hooks and internal functions need by the module.
 */

// Defines the consent bitmap
define('AAKB_SURVEY_NO_CONSENT', 1);
define('AAKB_SURVEY_USER_SATISFACTION', 2);
define('AAKB_SURVEY_NEWSLETTER', 4);

/**
 * Implements hook_permission().
 */
function aakb_survey_permission() {
  return array(
    'administer aakb survey' => array(
      'title' => t('Administer Aakb survey'),
      'description' => t('Perform administration tasks.'),
    ),
    'export aakb survey' => array(
      'title' => t('Export Aakb survey'),
      'description' => t('Export data from collected consent.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function aakb_survey_menu() {
  $items = array();

  $path = drupal_get_path('module', 'aakb_survey');

  $items['admin/config/people/survey'] = array(
    'title' => 'Aakb survey',
    'description' => 'Aakb survey configuration',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('aakb_survey_admin_form'),
    'access arguments' => array('administer aakb survey'),
    'file' => 'aakb_survey.admin.inc',
    'file path' => $path . '/includes',
  );

  $items['admin/config/people/survey/config'] = array(
    'title' => 'Configuration',
    'description' => 'Aakb survey config',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/config/people/survey/export'] = array(
    'title' => 'Export',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'aakb_survey_admin_export',
    'access arguments' => array('administer aakb survey'),
    'file' => 'aakb_survey.admin.inc',
    'file path' => $path . '/includes',
    'weight' => -15,
  );

  $items['admin/config/people/survey/send'] = array(
    'title' => 'Send',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'aakb_survey_admins_send',
    'access arguments' => array('administer aakb survey'),
    'file' => 'aakb_survey.admin.inc',
    'file path' => $path . '/includes',
    'weight' => -20,
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function aakb_survey_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'aakb_survey') . '/includes',
  );
}

/**
 * Implements hook_theme().
 */
function aakb_survey_theme($existing, $type, $theme, $path) {
  return array(
    'aakb_survey_export' => array(
      'variables' => array(
        'types' => NULL,
        'counts' => NULL,
        'links' => NULL,
      ),
      'template' => 'templates/aakb-survey-export'
    ),
    'aakb_survey_send' => array(
      'variables' => array(
        'users' => 0,
        'show_send' => FALSE,
      ),
      'template' => 'templates/aakb-survey-send',
    )
  );
}

/**
 * Get statistic about a consent type.
 *
 * @param int $type
 *   The consent type to get statistic for.
 */
function _aakb_survey_stats($type = AAKB_SURVEY_USER_SATISFACTION) {
  // @TODO: Change this to use the query builder.
  $query = db_query('SELECT count(*) FROM {aakb_survey} WHERE consent & :type', array(':type' => $type));
  return $query->fetchField();
}

/**
 * Count the number of not notified users in the database.
 *
 * @return int
 *   The number of users.
 */
function _aakb_survey_not_notified_users() {
  $query = db_select('aakb_survey', 's')
    ->fields('s', array('id'))
    ->condition('notified', 0, '=');

  return $query->countQuery()->execute()->fetchField();
}

/**
 * Define the different consent types.
 *
 * @return array
 *   The bitmap key as index and assoc. array with information.
 */
function _aakb_survey_consent_types() {
  return array(
    AAKB_SURVEY_USER_SATISFACTION => array(
      'title' => t('User satisfaction consent'),
      'description' => t('Yearly user satisfaction survey from the library.'),
    ),
    AAKB_SURVEY_NEWSLETTER => array(
      'title' => t('User newsletter consent'),
      'description' => t('Newsletters and survey from the municipality.'),
    ),
  );
}