<?php

function aakb_survey_admin_status() {
  return '';
}

function aakb_survey_admin_template_form() {
  $form = array();
  return system_settings_form($form);
}

function aakb_survey_admin_export_form() {
  $form = array();
  return system_settings_form($form);
}

function aakb_survey_admin_landing_form() {
  $form = array();
  return system_settings_form($form);
}

function aakb_survey_admins_send_form() {
  $form = array();
  return system_settings_form($form);
}